# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 680))
        MainWindow.setStyleSheet("\n"
"    QMainWindow, QWidget#centralwidget {\n"
"        background-color: #1a1a1a;\n"
"        color: #e0e0e0;\n"
"    }\n"
"    QWidget {\n"
"        font-family: \'Segoe UI\', \'Roboto\', sans-serif;\n"
"        font-size: 10pt;\n"
"    }\n"
"    QTabWidget::pane {\n"
"        border: 1px solid #333;\n"
"        background: #252525;\n"
"        border-radius: 14px;\n"
"        margin: 10px;\n"
"    }\n"
"    QTabBar::tab {\n"
"        background: #333;\n"
"        padding: 14px 32px;\n"
"        margin: 4px;\n"
"        border-radius: 12px;\n"
"        color: #bbb;\n"
"        min-width: 140px;\n"
"    }\n"
"    QTabBar::tab:selected {\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #4a90ff, stop:1 #357abd);\n"
"        color: white;\n"
"        font-weight: bold;\n"
"    }\n"
"    QLabel {\n"
"        color: #e0e0e0;\n"
"        background: transparent;\n"
"        font-weight: 500;\n"
"    }\n"
"    QTextBrowser {\n"
"        background-color: #2b2b2b;\n"
"        color: #e0e0e0;\n"
"        border: 1px solid #444;\n"
"        border-radius: 10px;\n"
"        padding: 6px;\n"
"    }\n"
"    QTextBrowser:focus {\n"
"        border: 1px solid #4a90ff;\n"
"    }\n"
"    QLineEdit, QComboBox, QListWidget, QListView {\n"
"        background-color: #333;\n"
"        border: 1px solid #555;\n"
"        border-radius: 10px;\n"
"        padding: 10px;\n"
"        color: white;\n"
"        font-size: 10pt;\n"
"    }\n"
"    QPlainTextEdit {\n"
"        background-color: #1e1e1e;\n"
"        border: 1px solid #555;\n"
"        border-radius: 10px;\n"
"        padding: 6px;\n"
"        color: #e0e0e0;\n"
"        font-size: 10pt;\n"
"    }\n"
"    QLineEdit:focus, QPlainTextEdit:focus, QComboBox:focus {\n"
"        border: 2px solid #4a90ff;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"        width: 30px;\n"
"    }\n"
"    QComboBox::down-arrow {\n"
"        image: url(:/icons/down-arrow.png);\n"
"    }\n"
"    /* Alternador de idioma — minimalista, sem fundo, com bandeirinha */\n"
"    QComboBox#combo_lang, QComboBox#combo_lang:!editable, QComboBox#combo_lang:!editable:on {\n"
"        background-color: transparent;\n"
"        background: transparent;\n"
"        border: none;\n"
"        border-radius: 6px;\n"
"        padding: 2px 6px;\n"
"        color: #8a8a8a;\n"
"        font-size: 9pt;\n"
"        font-weight: 500;\n"
"        font-family: 'Segoe UI Emoji', 'Segoe UI', sans-serif;\n"
"        min-width: 82px;\n"
"        max-width: 104px;\n"
"    }\n"
"    QComboBox#combo_lang:hover {\n"
"        background-color: rgba(255, 255, 255, 0.06);\n"
"        background: rgba(255, 255, 255, 0.06);\n"
"        color: #e0e0e0;\n"
"    }\n"
"    QComboBox#combo_lang:focus, QComboBox#combo_lang:on {\n"
"        border: none;\n"
"        background-color: rgba(255, 255, 255, 0.06);\n"
"        background: rgba(255, 255, 255, 0.06);\n"
"    }\n"
"    QComboBox#combo_lang::drop-down {\n"
"        border: none;\n"
"        width: 14px;\n"
"        background: transparent;\n"
"        background-color: transparent;\n"
"    }\n"
"    QComboBox#combo_lang::down-arrow {\n"
"        width: 0;\n"
"        height: 0;\n"
"        border-left: 4px solid transparent;\n"
"        border-right: 4px solid transparent;\n"
"        border-top: 5px solid #777;\n"
"        margin-right: 6px;\n"
"        margin-top: 2px;\n"
"        image: none;\n"
"    }\n"
"    QComboBox#combo_lang QAbstractItemView {\n"
"        background-color: #2b2b2b;\n"
"        color: #e0e0e0;\n"
"        border: 1px solid #444;\n"
"        selection-background-color: #357abd;\n"
"        selection-color: white;\n"
"        outline: 0;\n"
"        padding: 2px;\n"
"    }\n"
"    /* FIX Windows: popups brancos e viewport branco */\n"
    "    QComboBox QAbstractItemView, QListView, QListWidget {\n"
    "        background-color: #2b2b2b;\n"
    "        color: #e0e0e0;\n"
    "        border: 1px solid #444;\n"
    "        selection-background-color: #357abd;\n"
    "        selection-color: white;\n"
    "        outline: 0;\n"
    "    }\n"
    "    QListWidget::item {\n"
    "        padding: 6px;\n"
    "        border-radius: 6px;\n"
    "    }\n"
    "    QListWidget::item:selected {\n"
    "        background: #357abd;\n"
    "        color: white;\n"
    "    }\n"
    "    QListWidget::item:hover {\n"
    "        background: #3a3a3a;\n"
    "    }\n"
    "    QAbstractScrollArea::viewport {\n"
    "        background: transparent;\n"
    "    }\n"
    "    QScrollBar:vertical, QScrollBar:horizontal {\n"
    "        background: #2a2a2a;\n"
    "        border: none;\n"
    "        border-radius: 4px;\n"
    "    }\n"
    "    QScrollBar::handle {\n"
    "        background: #555;\n"
    "        border-radius: 4px;\n"
    "    }\n"
    "    QScrollBar::handle:hover {\n"
    "        background: #666;\n"
    "    }\n"
    "    QStatusBar {\n"
    "        background: #1a1a1a;\n"
    "        color: #999;\n"
    "        border-top: 1px solid #333;\n"
    "    }\n"
    "    QPushButton {\n"

"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #5ba3ff, stop:1 #3d85e0);\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 10px;\n"
"        padding: 12px 24px;\n"
"        font-weight: bold;\n"
"        font-size: 11pt;\n"
"    }\n"
"    QDialog, QMessageBox, QProgressDialog {\n"
"        background-color: #252525;\n"
"        color: #e0e0e0;\n"
"    }\n"
"    QProgressBar {\n"
"        background: #2b2b2b;\n"
"        border: 1px solid #444;\n"
"        border-radius: 6px;\n"
"        color: white;\n"
"    }\n"
"    QProgressBar::chunk {\n"
"        background: #4a90ff;\n"
"        border-radius: 4px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #6bb3ff, stop:1 #4a95f0);\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background: #357abd;\n"
"    }\n"
"    QPushButton#btn_pick_source, QPushButton#btn_pick_dest {\n"
"        padding: 2px 4px;\n"
"        font-size: 16pt;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton#btn_stop_forward {\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ff5555, stop:1 #cc0000);\n"
"    }\n"
"    QLCDNumber {\n"
"        background: #111;\n"
"        color: #00ff88;\n"
"        border-radius: 12px;\n"
"        border: 1px solid #00aa00;\n"
"        padding: 8px;\n"
"    }\n"
"    QLCDNumber#failed_count {\n"
"        color: #ff4000;\n"
"    }\n"
"    QFrame#status_frame {\n"
"        background: #222;\n"
"        border: 1px solid #444;\n"
"        border-radius: 12px;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(15, 15, 15, 15)
        self.mainLayout.setSpacing(12)
        self.mainLayout.setObjectName("mainLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        spacerItemHeader = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItemHeader)
        self.combo_lang = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_lang.setObjectName("combo_lang")
        self.combo_lang.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.combo_lang.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.combo_lang.setToolTip("Language / Idioma")
        self.combo_lang.setMaximumWidth(102)
        self.combo_lang.setMinimumWidth(88)
        self.headerLayout.addWidget(self.combo_lang)
        self.mainLayout.addLayout(self.headerLayout)
        self.tab_account = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tab_account.setObjectName("tab_account")
        self.Account = QtWidgets.QWidget()
        self.Account.setObjectName("Account")
        self.accountLayout = QtWidgets.QHBoxLayout(self.Account)
        self.accountLayout.setObjectName("accountLayout")
        self.leftControls = QtWidgets.QVBoxLayout()
        self.leftControls.setObjectName("leftControls")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_add_account = QtWidgets.QLabel(parent=self.Account)
        self.label_add_account.setObjectName("label_add_account")
        self.hboxlayout.addWidget(self.label_add_account)
        self.account_input_add = QtWidgets.QLineEdit(parent=self.Account)
        self.account_input_add.setObjectName("account_input_add")
        self.hboxlayout.addWidget(self.account_input_add)
        self.add_account = QtWidgets.QPushButton(parent=self.Account)
        self.add_account.setObjectName("add_account")
        self.hboxlayout.addWidget(self.add_account)
        self.leftControls.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_remove_account = QtWidgets.QLabel(parent=self.Account)
        self.label_remove_account.setObjectName("label_remove_account")
        self.hboxlayout1.addWidget(self.label_remove_account)
        self.remove_account_input = QtWidgets.QLineEdit(parent=self.Account)
        self.remove_account_input.setObjectName("remove_account_input")
        self.hboxlayout1.addWidget(self.remove_account_input)
        self.remove_account_bot = QtWidgets.QPushButton(parent=self.Account)
        self.remove_account_bot.setObjectName("remove_account_bot")
        self.hboxlayout1.addWidget(self.remove_account_bot)
        self.leftControls.addLayout(self.hboxlayout1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.leftControls.addItem(spacerItem)
        self.update_number_bot = QtWidgets.QPushButton(parent=self.Account)
        self.update_number_bot.setObjectName("update_number_bot")
        self.leftControls.addWidget(self.update_number_bot)
        self.accountLayout.addLayout(self.leftControls)
        self.helpSection = QtWidgets.QVBoxLayout()
        self.helpSection.setObjectName("helpSection")
        self.help_account_add = QtWidgets.QTextBrowser(parent=self.Account)
        self.help_account_add.setObjectName("help_account_add")
        self.helpSection.addWidget(self.help_account_add)
        self.help_remove_account = QtWidgets.QTextBrowser(parent=self.Account)
        self.help_remove_account.setObjectName("help_remove_account")
        self.helpSection.addWidget(self.help_remove_account)
        self.accountLayout.addLayout(self.helpSection)
        self.listSection = QtWidgets.QVBoxLayout()
        self.listSection.setObjectName("listSection")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.Account)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.listSection.addWidget(self.textBrowser_2)
        self.list_account_ac = QtWidgets.QListWidget(parent=self.Account)
        self.list_account_ac.setMinimumSize(QtCore.QSize(260, 0))
        self.list_account_ac.setObjectName("list_account_ac")
        self.listSection.addWidget(self.list_account_ac)
        self.lcdNumber = QtWidgets.QLCDNumber(parent=self.Account)
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setObjectName("lcdNumber")
        self.listSection.addWidget(self.lcdNumber)
        self.accountLayout.addLayout(self.listSection)
        self.tab_account.addTab(self.Account, "")
        self.ForwardTab = QtWidgets.QWidget()
        self.ForwardTab.setObjectName("ForwardTab")
        self.forwardLayout = QtWidgets.QVBoxLayout(self.ForwardTab)
        self.forwardLayout.setSpacing(16)
        self.forwardLayout.setObjectName("forwardLayout")
        self.label = QtWidgets.QLabel(parent=self.ForwardTab)
        self.label.setObjectName("label")
        self.forwardLayout.addWidget(self.label)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.label1 = QtWidgets.QLabel(parent=self.ForwardTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.hboxlayout2.addWidget(self.label1)
        self.combo_select_account = QtWidgets.QComboBox(parent=self.ForwardTab)
        self.combo_select_account.setMinimumSize(QtCore.QSize(300, 0))
        self.combo_select_account.setObjectName("combo_select_account")
        self.hboxlayout2.addWidget(self.combo_select_account)
        self.forwardLayout.addLayout(self.hboxlayout2)
        self.gridInputs = QtWidgets.QGridLayout()
        self.gridInputs.setObjectName("gridInputs")
        self.label2 = QtWidgets.QLabel(parent=self.ForwardTab)
        self.label2.setObjectName("label2")
        self.gridInputs.addWidget(self.label2, 0, 0, 1, 1)
        self.source_channel_input = QtWidgets.QLineEdit(parent=self.ForwardTab)
        self.source_channel_input.setObjectName("source_channel_input")
        self.gridInputs.addWidget(self.source_channel_input, 0, 1, 1, 1)
        self.btn_pick_source = QtWidgets.QPushButton(parent=self.ForwardTab)
        self.btn_pick_source.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_pick_source.setObjectName("btn_pick_source")
        self.gridInputs.addWidget(self.btn_pick_source, 0, 2, 1, 1)
        self.label3 = QtWidgets.QLabel(parent=self.ForwardTab)
        self.label3.setObjectName("label3")
        self.gridInputs.addWidget(self.label3, 1, 0, 1, 1)
        self.dest_channel_input = QtWidgets.QLineEdit(parent=self.ForwardTab)
        self.dest_channel_input.setObjectName("dest_channel_input")
        self.gridInputs.addWidget(self.dest_channel_input, 1, 1, 1, 1)
        self.btn_pick_dest = QtWidgets.QPushButton(parent=self.ForwardTab)
        self.btn_pick_dest.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_pick_dest.setObjectName("btn_pick_dest")
        self.gridInputs.addWidget(self.btn_pick_dest, 1, 2, 1, 1)
        self.forwardLayout.addLayout(self.gridInputs)
        self.hboxlayout3 = QtWidgets.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.btn_start_forward = QtWidgets.QPushButton(parent=self.ForwardTab)
        self.btn_start_forward.setMinimumSize(QtCore.QSize(200, 50))
        self.btn_start_forward.setObjectName("btn_start_forward")
        self.hboxlayout3.addWidget(self.btn_start_forward)
        self.btn_stop_forward = QtWidgets.QPushButton(parent=self.ForwardTab)
        self.btn_stop_forward.setMinimumSize(QtCore.QSize(120, 50))
        self.btn_stop_forward.setObjectName("btn_stop_forward")
        self.hboxlayout3.addWidget(self.btn_stop_forward)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout3.addItem(spacerItem1)
        self.forwardLayout.addLayout(self.hboxlayout3)
        self.status_frame = QtWidgets.QFrame(parent=self.ForwardTab)
        self.status_frame.setObjectName("status_frame")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.status_frame)
        self.vboxlayout.setObjectName("vboxlayout")
        self.lbl_status = QtWidgets.QLabel(parent=self.status_frame)
        self.lbl_status.setObjectName("lbl_status")
        self.vboxlayout.addWidget(self.lbl_status)
        self.lbl_last_sync = QtWidgets.QLabel(parent=self.status_frame)
        self.lbl_last_sync.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_last_sync.setObjectName("lbl_last_sync")
        self.vboxlayout.addWidget(self.lbl_last_sync)
        self.lbl_last_message = QtWidgets.QLabel(parent=self.status_frame)
        self.lbl_last_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_last_message.setObjectName("lbl_last_message")
        self.vboxlayout.addWidget(self.lbl_last_message)
        self.hboxlayout4 = QtWidgets.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.label4 = QtWidgets.QLabel(parent=self.status_frame)
        self.label4.setObjectName("label4")
        self.hboxlayout4.addWidget(self.label4)
        self.success_count = QtWidgets.QLCDNumber(parent=self.status_frame)
        self.success_count.setDigitCount(7)
        self.success_count.setObjectName("success_count")
        self.hboxlayout4.addWidget(self.success_count)
        self.label5 = QtWidgets.QLabel(parent=self.status_frame)
        self.label5.setObjectName("label5")
        self.hboxlayout4.addWidget(self.label5)
        self.failed_count = QtWidgets.QLCDNumber(parent=self.status_frame)
        self.failed_count.setDigitCount(7)
        self.failed_count.setObjectName("failed_count")
        self.hboxlayout4.addWidget(self.failed_count)
        self.label6 = QtWidgets.QLabel(parent=self.status_frame)
        self.label6.setObjectName("label6")
        self.hboxlayout4.addWidget(self.label6)
        self.total_count = QtWidgets.QLCDNumber(parent=self.status_frame)
        self.total_count.setDigitCount(8)
        self.total_count.setObjectName("total_count")
        self.hboxlayout4.addWidget(self.total_count)
        self.vboxlayout.addLayout(self.hboxlayout4)
        self.forwardLayout.addWidget(self.status_frame)
        self.forward_log = QtWidgets.QPlainTextEdit(parent=self.ForwardTab)
        self.forward_log.setReadOnly(True)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.forward_log.setFont(font)
        self.forward_log.setObjectName("forward_log")
        self.forwardLayout.addWidget(self.forward_log)
        self.tab_account.addTab(self.ForwardTab, "")
        self.mainLayout.addWidget(self.tab_account)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Telegram Restricted Channels Message Forwarder by https://erfan4lx.com"))
        MainWindow.setWindowIcon(QIcon("icon.jpg"))
        self.account_input_add.setPlaceholderText(_translate("MainWindow", "+123456789"))
        self.add_account.setText(_translate("MainWindow", "Add account"))
        self.remove_account_input.setPlaceholderText(_translate("MainWindow", "+123456789"))
        self.remove_account_bot.setText(_translate("MainWindow", "Remove account"))
        self.update_number_bot.setText(_translate("MainWindow", "Update Number"))
        self.help_account_add.setHtml(_translate("MainWindow", "<p><b>This section is for adding an account.</b></p>"))
        self.help_remove_account.setHtml(_translate("MainWindow", "<p><b>This section is for deleting an existing account in the program.</b></p>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<p align=\"center\"><b>List Accounts</b></p>"))
        self.tab_account.setTabText(self.tab_account.indexOf(self.Account), _translate("MainWindow", "   Account   "))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700; color:#4a90ff;\">Restricted Channel to Channel Forwarder</span></p></body></html>"))
        self.label1.setText(_translate("MainWindow", "Select Account:"))
        self.combo_select_account.setPlaceholderText(_translate("MainWindow", "Choose an account to forward with..."))
        self.label2.setText(_translate("MainWindow", "Source Channel:"))
        self.source_channel_input.setPlaceholderText(_translate("MainWindow", "@durov or -1001234567890"))
        self.label3.setText(_translate("MainWindow", "Destination Channel:"))
        self.dest_channel_input.setPlaceholderText(_translate("MainWindow", "@my_channel or -1009876543210"))
        self.btn_start_forward.setText(_translate("MainWindow", "Start Forwarding"))
        self.btn_stop_forward.setText(_translate("MainWindow", "Stop"))
        self.lbl_status.setText(_translate("MainWindow", "<p align=\"center\"><b>Status: Stopped</b></p>"))
        self.lbl_status.setStyleSheet(_translate("MainWindow", "color: #ff5555; font-size: 14pt; font-weight: bold;"))
        self.lbl_last_message.setText(_translate("MainWindow", "Last forwarded: No message yet"))
        self.label_add_account.setText(_translate("MainWindow", "Add:"))
        self.label_remove_account.setText(_translate("MainWindow", "Del:"))
        self.lbl_last_sync.setText(_translate("MainWindow", ""))
        self.lbl_last_message.setStyleSheet(_translate("MainWindow", "color: #00ff88; font-size: 12pt;"))
        self.label4.setText(_translate("MainWindow", "Success:"))
        self.label5.setText(_translate("MainWindow", "Failed:"))
        self.label6.setText(_translate("MainWindow", "Total:"))
        self.forward_log.setPlaceholderText(_translate("MainWindow", "Forwarding logs will appear here...\\nExample: [2025-04-05 12:30:15] Message ID 1234 forwarded successfully"))
        self.tab_account.setTabText(self.tab_account.indexOf(self.ForwardTab), _translate("MainWindow", "   Forward Messages   "))
        self.btn_pick_source.setText(_translate("MainWindow", "+"))
        self.btn_pick_dest.setText(_translate("MainWindow", "+"))
        self.combo_lang.addItems([_translate("MainWindow", "EN"), _translate("MainWindow", "PT-BR")])
